language: python
python:
  - "3.3"
  - "3.4"
  - "3.6"

install:
  - pip install coveralls
  - pip install .

script:
  - source tests/demo.env
  - coverage run --source openmrsapi setup.py test

after_success:
  - coveralls